#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Add link for init PID 1.

ln -sv /sbin/openrc-init /sbin/init


# -- Edit vanilla rc.conf with our default values.

sed -i 's/#rc_parallel="NO"/rc_parallel="YES"/g' /etc/rc.conf
sed -i 's+#rc_shell=/bin/sh+rc_shell=/bin/zsh+g' /etc/rc.conf
sed -i 's/#rc_logger="NO"/rc_logger="YES"/g' /etc/rc.conf
sed -i 's+#rc_log_path="/var/log/rc.log"+rc_log_path="/var/log/rc.log"+g' /etc/rc.conf
sed -i 's+#rc_crashed_start=YES+rc_crashed_start=YES+g' /etc/rc.conf
sed -i 's/#unicode="NO"/unicode="YES"/g' /etc/rc.conf
sed -i 's/#rc_send_sighup="NO"/rc_send_sighup="YES"/g' /etc/rc.conf
sed -i 's/#rc_timeout_stopsec="90"/rc_timeout_stopsec="10"/g' /etc/rc.conf
sed -i 's/#rc_send_sigkill="YES"/rc_send_sigkill="YES"/g' /etc/rc.conf
sed -i 's/#rc_controller_cgroups="YES"/rc_controller_cgroups="YES"/g' /etc/rc.conf
sed -i 's/#rc_cgroup_mode="unified"/rc_cgroup_mode="unified"/g' /etc/rc.conf
sed -i 's/#rc_cgroup_controllers=""/rc_cgroup_controllers="cgroup_root openrc none cpuset cpu cpuacct blkio io memory devices freezer net_cls perf_event net_prio hugetlb pids rdma misc cgroup"/g' /etc/rc.conf


# -- Explicitly control shutdown and boot options.

cat << 'EOF' >> /etc/rc.conf

# Set to "poweroff" (default) or "halt".
rc_halt_action="poweroff"

# Set to "YES" (default) to shut down network interfaces before halting.
rc_down_interfaces="YES"

# Set to "YES" to create /run/nologin at boot to delay user logins.
rc_delaylogin="YES"

# Set to "YES" to force fsck to run even if the filesystem seems clean.
# rc_force_fsck="NO"

# Set to "YES" to have fsck automatically fix errors without asking (-y).
# If "NO" (default), it will only fix safe errors (-a).
# rc_fsck_fix="NO"

# Set to "YES" to get a maintenance shell (sulogin) before boot.
# rc_sulogin="NO"
EOF


# -- Add ttys.

for i in {2..6}; do
  ln -sv "/etc/init.d/agetty" "/etc/init.d/agetty.tty${i}"
  rc-update add "agetty.tty${i}" default
done


# -- Edit vanilla agetty with our default values.

sed -i 's/#baud=""/baud="38400"/g' /etc/conf.d/agetty
sed -i 's/#term_type="linux"/term_type="linux"/g' /etc/conf.d/agetty
sed -i 's|#agetty_options=""|agetty_options="-pl /bin/login"|g' /etc/conf.d/agetty


# -- Add services to the appropriate runlevels using rc-update.

echo "Adding OpenRC services to runlevels..."

# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## System Initialization (sysinit)                                                                                                               #
# -- These services run first to prepare the base system (mounting /proc, /sys, /dev, starting eudev, etc.).                                       #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add apparmor-openrc sysinit
rc-update add bootmisc sysinit
rc-update add cgroups sysinit
rc-update add dev sysinit
rc-update add eudev-openrc sysinit
rc-update add hostname sysinit
rc-update add modules sysinit
rc-update add procfs sysinit
rc-update add sysctl sysinit
rc-update add sysfs sysinit


# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Boot-time Services (boot)                                                                                                                     #
# -- These services run after sysinit to mount filesystems, load seeds, etc.                                                                       #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add bootlogs boot
rc-update add brightness boot
rc-update add configfs boot
rc-update add cryptmount boot
rc-update add device-mapper boot
rc-update add dmcrypt boot
rc-update add dmeventd boot
rc-update add fsck boot
rc-update add localmount boot
rc-update add root boot
rc-update add rsyslog-openrc boot
rc-update add swap boot
rc-update add swclock boot
rc-update add urandom boot


# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Main Services (default)                                                                                                                       #
# -- These are the standard, user-facing services that run in a normal multi-user session.                                                         #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add acpi-support-openrc default
rc-update add acpid-openrc default
rc-update add dbus-openrc default
rc-update add elogind-openrc default
rc-update add greetd-openrc default
rc-update add local default
rc-update add mountbinds default
rc-update add netmount default
rc-update add network-manager default
rc-update add plymouth-openrc default
rc-update add uuid default
rc-update add console-setup-openrc default
rc-update add keyboard-setup-openrc default
rc-update add gpu-vendor-check default
rc-update add firewalld-openrc default
rc-update add dnscrypt-proxy default
rc-update add scx-dynamic-scheduler default


# ------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Asynchronous Services (async)                                                                                                                #
# -- A custom runlevel for services that can start in the background.                                                                             #
# ------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add bcm-drv async
rc-update add bluetooth-openrc async
rc-update add cron-openrc async
rc-update add rapl-power async
rc-update add thp-settings async
rc-update add usbmuxd async
rc-update add rngd-openrc async
rc-update add ananicy-cpp async
rc-update add eudev-rules-refresh async
rc-update add debugfs default
rc-update add ntpsec-openrc default
rc-update add nohang-openrc default
rc-update add power-profiles-daemon default
rc-update add powertop default
rc-update add sudo-openrc default


# --------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Shutdown Services (shutdown)                                                                                                                   #
# -- These services have `stop()` actions that run when the system is halting or rebooting.                                                         #
# --------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add brightness shutdown
rc-update add hwclock shutdown
rc-update add savecache shutdown
rc-update add umountfs shutdown
rc-update add urandom shutdown


# -- Rebuild the dependency tree after making all changes.

rc-update -u
