#! /bin/bash


# -- Remove whatever is currently in the runlevels.
# -- By default, upstream creates links but we don't because the links brake when creating the SquashFS.

/bin/rm -f /etc/runlevels/default/* /etc/runlevels/nonetwork/* /etc/runlevels/off/* /etc/runlevels/recovery/* /etc/runlevels/sysinit/* /etc/runlevels/boot/*


# -- Create custom runlevel "async" directory and stack it to default.

mkdir /etc/runlevels/async && rc-update add -s async default


# -- Copy init scripts from init.d to OpenRC runlevels.

/bin/cp /etc/init.d/{acpi-support,acpid,console-setup.sh,dbus,debugfs-mount-openrc,elogind,fprintd-openrc,mountbinds,network-manager,nohang-desktop-openrc,ntpsec-openrc,plymouth-openrc,powertop-openrc,rmnologin,sddm,sudo,tlp,uuidd} /etc/runlevels/default/ || true

/bin/cp /etc/init.d/{avahi-daemon-openrc,bluez-obexd-openrc,bluez-meshd-openrc,bluez-openrc,cron,cups,irqbalance,nmbd,preload,rsyslog-openrc,smbd,thp-settings,usbmuxd-openrc} /etc/runlevels/async/ || true

# /bin/cp /etc/init.d/rc.local /etc/runlevels/nonetwork/local || true

/bin/cp /etc/init.d/{savecache,sendsigs,umountfs,umountnfs.sh,umountroot} /etc/runlevels/off || true

# /bin/cp /etc/init.d/{bootlogs,killprocs,single} /etc/runlevels/recovery || true

/bin/cp /etc/init.d/{apparmor,bootmisc.sh,brightness,cgroups,checkroot-bootclean.sh,checkroot.sh,eudev,hostname.sh,hwclock.sh,keyboard-setup.sh,kmod,mount-configfs,mountall-bootclean.sh,mountall.sh,mountdevsubfs.sh,mountkernfs.sh,mountnfs.sh,networking,plymouth-log,procps,selinux-autorelabel,ufw,urandom,x11-common} /etc/runlevels/sysinit || true

/bin/cp /etc/init.d/{cryptdisks,cryptdisks-early,cryptmount-openrc,device-mapper-openrc,dmcrypt-openrc,dmeventd-openrc} /etc/runlevels/boot || true
