#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Clear all runlevels to ensure a clean state.

rm -f /etc/runlevels/default/* \
    /etc/runlevels/shutdown/* \
    /etc/runlevels/boot/* \
    /etc/runlevels/sysinit/*


# -- Create custom runlevel "async" directory if it doesn't exist and stack it to the default runlevel.

mkdir -p /etc/runlevels/async && rc-update -s add async default
