#!/usr/bin/env bash

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2025> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# -- Remove whatever is currently in the runlevels to ensure a clean state.
# -- This prevents stale links from previous installations.

/bin/rm -f /etc/runlevels/default/* \
           /etc/runlevels/shutdown/* \
           /etc/runlevels/boot/* \
           /etc/runlevels/sysinit/*


# -- Create custom runlevel "async" directory if it doesn't exist and stack it to default.

mkdir -p /etc/runlevels/async && rc-update -s add async default


# -- Add services to the appropriate runlevels using rc-update.

echo "Adding OpenRC services to runlevels..."

# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## System Initialization (sysinit)                                                                                                               #
# -- These services run first to prepare the base system (mounting /proc, /sys, /dev, starting udev, etc.).                                        #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add apparmor-openrc sysinit
rc-update add bootmisc sysinit
rc-update add cgroups sysinit
rc-update add dev sysinit
rc-update add hostname sysinit
rc-update add modules sysinit
rc-update add procfs sysinit
rc-update add sysctl sysinit
rc-update add sysfs sysinit
rc-update add udev sysinit


# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Boot-time Services (boot)                                                                                                                     #
# -- These services run after sysinit to mount filesystems, load seeds, etc.                                                                       #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add bootlogs boot
rc-update add brightness boot
rc-update add configfs boot
rc-update add cryptmount boot
rc-update add device-mapper boot
rc-update add dmcrypt boot
rc-update add dmeventd boot
rc-update add fsck boot
rc-update add localmount boot
rc-update add root boot
rc-update add swap boot
rc-update add swclock boot
rc-update add urandom boot


# -------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Main Services (default)                                                                                                                       #
# -- These are the standard, user-facing services that run in a normal multi-user session.                                                         #
# -------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add acpi-support-openrc default
rc-update add acpid-openrc default
rc-update add dbus-openrc default
rc-update add debugfs default
rc-update add elogind-openrc default
rc-update add greetd default
rc-update add local default
rc-update add mountbinds default
rc-update add netmount default
rc-update add network-manager default
rc-update add nohang-desktop-openrc default
rc-update add ntpsec-openrc default
rc-update add plymouth-openrc default
rc-update add power-profiles-daemon-openrc default
rc-update add powertop default
rc-update add sudo default
rc-update add uuidd default


# ------------------------------------------------------------------------------------------------------------------------------------------------#
# ## Asynchronous Services (async)                                                                                                                #
# -- A custom runlevel for services that can start in the background.                                                                             #
# ------------------------------------------------------------------------------------------------------------------------------------------------#
rc-update add bcm-drv async
rc-update add bluetooth-meshd-openrc async
rc-update add bluetooth-obexd-openrc async
rc-update add bluetooth-openrc async
rc-update add cron-openrc async
rc-update add nvidia-powerd async
rc-update add rapl-power async
rc-update add rsyslog-openrc async
rc-update add thp-settings async
rc-update add usbmuxd async


# ------------------------------------------------------------------------------------------------------------------------------------------------- #
# ## Shutdown Services (shutdown)                                                                                                                   #
# -- These services have `stop()` actions that run when the system is halting or rebooting.                                                         #
# ------------------------------------------------------------------------------------------------------------------------------------------------- #
rc-update add brightness shutdown
rc-update add hwclock shutdown
rc-update add savecache shutdown
rc-update add umountfs shutdown
rc-update add urandom shutdown


# -- Rebuild the dependency tree after making all changes.

rc-update
